services:
  ecs-controller:
    build: .
    container_name: ecs-control
    restart: always
    ports:
      - "${PORT:-43210}:${PORT:-43210}"
    volumes:
      - ./data:/var/www/html/data
    environment:
      - PORT=${PORT:-43210}
      - TZ=Asia/Shanghai
    dns:
      - 223.5.5.5
      - 114.114.114.114
